/*
 * File: app/store/IncompleteTortletsStore.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.IncompleteTortletsStore', {
    extend: 'Ext.data.Store',
    alias: 'store.incompleteTortletsStore',

    requires: [
        'MyApp.model.Tortlet'
    ],

    config: {
        model: 'MyApp.model.Tortlet',
        storeId: 'incompleteTortletsStore',
        proxy: {
            type: 'rest',
            enablePagingParams: false,
            url: 'http://dummy.url',
            headers: {
                Accept: 'application/json'
            },
            reader: {
                type: 'json'
            }
        },
        grouper: {
            groupFn: function(item) {
                var d = new Date(item.get('createdOn'));
                var datePart = d.getDate();
                var monthPart = d.getMonth() + 1; //Months are zero based
                var today = MyApp.app.weekdayArray[d.getDay()] + "," + monthPart  + "/" + datePart;

                return today;
            },
            sortProperty: 'createdOn'
        },
        filters: {
            filterFn: function(item) {
                var d = new Date(item.get('createdOn'));
                var createdDate = d.getDate();
                var createdMonth = d.getMonth() + 1; //Months are zero based
                var createdYear = d.getFullYear();
                var createdOn = createdMonth  + "/" + createdDate + "/" + createdYear;

                var today = MyApp.app.getToday();
                return !(today === createdOn);
            }
        }
    }
});