/*
 * File: app/store/TodaysTortletsStore.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.TodaysTortletsStore', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.Tortlet'
    ],

    config: {
        model: 'MyApp.model.Tortlet',
        storeId: 'todaysTortletsStore',
        proxy: {
            type: 'rest',
            enablePagingParams: false,
            url: 'http://dummy.url',
            headers: {
                Accept: 'application/json'
            },
            appendId: false,
            reader: {
                type: 'json'
            }
        },
        sorters: {
            sorterFn: function(first, second) {
                var score1 = first.data.tortoise.latestTortoiseScore;
                var score2 = second.data.tortoise.latestTortoiseScore;

                if(score1 === score2){

                    var createdCount1 = first.data.tortoise.tortletsCreatedCount;
                    var createdCount2 = second.data.tortoise.tortletsCreatedCount;
                    return createdCount1 < createdCount2 ? 1 : (createdCount1 === createdCount2 ? 0 : -1);

                }else{

                    return score1 > score2 ? 1 : (score1 === score2 ? 0 : -1);

                }
            },
            property: 'tortoise.dream.latestDreamScore'
        }
    }
});