/*
 * File: app/model/Tortlet.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.Tortlet', {
    extend: 'Ext.data.Model',
    alias: 'model.tortlet',

    requires: [
        'Ext.data.*',
        'Ext.data.*.*'
    ],
    uses: [
        'MyApp.model.Tortoise'
    ],

    config: {
        fields: [
            {
                name: 'title',
                type: 'string'
            },
            {
                name: 'completed',
                type: 'boolean'
            },
            {
                name: 'notes',
                type: 'string'
            },
            {
                name: 'version',
                type: 'int'
            }
        ],
        proxy: {
            type: 'rest',
            url: 'http://dummy.url',
            headers: {
                Accept: 'application/json'
            },
            appendId: false,
            reader: {
                type: 'json'
            },
            writer: {
                type: 'json'
            }
        },
        belongsTo: {
            model: 'MyApp.model.Tortoise',
            foreignKey: 'tortoise'
        }
    }
});