/*
 * File: app/model/Tortlet.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.Tortlet', {
    extend: 'Ext.data.Model',
    alias: 'model.tortlet',

    uses: [
        'MyApp.model.Tortoise'
    ],

    config: {
        fields: [
            {
                name: 'title',
                type: 'string'
            },
            {
                name: 'completed',
                type: 'boolean'
            },
            {
                name: 'notes',
                type: 'string'
            },
            {
                name: 'version',
                type: 'int'
            }
        ],
        belongsTo: {
            model: 'MyApp.model.Tortoise',
            foreignKey: 'tortoise'
        }
    }
});