/*
 * File: app/view/DreamDetails.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.DreamDetails', {
    extend: 'Ext.form.Panel',
    alias: 'widget.dreamDetails',

    config: {
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Dream',
                items: [
                    {
                        xtype: 'button',
                        name: 'dreamDetailsBackButton',
                        ui: 'back',
                        text: 'Back'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: 'I dream',
                items: [
                    {
                        xtype: 'textareafield',
                        height: 74,
                        html: '',
                        placeHolder: 'Become healthy and loose weight..'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: 'Bit More On This Dream',
                items: [
                    {
                        xtype: 'textareafield',
                        height: 78,
                        width: 280
                    },
                    {
                        xtype: 'button',
                        name: 'dreamDetailsTortoises',
                        ui: 'forward',
                        text: 'Tortoises'
                    },
                    {
                        xtype: 'selectfield',
                        label: 'Dream Color',
                        labelWidth: '40%',
                        options: [
                            {
                                text: 'White',
                                value: 'White'
                            },
                            {
                                text: 'Yellow',
                                value: 'Yellow'
                            },
                            {
                                text: 'Blue',
                                value: 'Blue'
                            },
                            {
                                text: 'Green',
                                value: 'Green'
                            },
                            {
                                text: 'Red',
                                value: 'Red'
                            },
                            
                        ]
                    }
                ]
            },
            {
                xtype: 'fieldset',
                items: [
                    {
                        xtype: 'button',
                        name: 'dreamDetailsStartDreaming',
                        ui: 'confirm',
                        text: 'Make It Happen !'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                items: [
                    {
                        xtype: 'button',
                        name: 'dreamDeleteButton',
                        ui: 'decline',
                        text: 'I am done ! (Delete)'
                    }
                ]
            }
        ]
    }

});