/*
 * File: app/view/HelpPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.HelpPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.helpPanel',

    config: {
        styleHtmlContent: true,
        scrollable: 'vertical',
        data: {
            appName: 'Tortlets',
            allowedDelayDays: 7,
            smallTseImg: '<img src="static/images/tortoise_smaller.gif"></img>'
        },
        tpl: [
            '{appName} helps you declare your dream or goal to yourself, ',
            'It lets you create weekly recurring activities (Tortoises) and ',
            'based on that creates "Tortlets" everyday. ',
            '<br/>',
            '<br/>',
            'It keeps record of how much you are doing and gives you',
            'score of each of your dream and you, as a dreamer. ',
            '<br/>',
            '<br/>',
            '{smallTseImg} Declare your dream/goal to yourself using Home tab and "Go" Button',
            '<br/>',
            '{smallTseImg} Create weekly “Tortoises”(recurring activities) for your dream',
            '<br/>',
            '{smallTseImg}The app will automatically generate Tortlets (Tortoise + Tasklet) ',
            'and will be ready for you every morning to work on that day',
            '<br/>',
            '{smallTseImg} Mark those Tortlets which you complete. ',
            'Just tap on the tortlets list item',
            '<br/>',
            '{smallTseImg} If you miss Tortlet to finish that day, you do have default {allowedDelayDays} ',
            'days to catch up. You will see pending list using "Pending" button ',
            'on Home tab',
            '<br/>',
            '{smallTseImg} If you dont finish Tortlets from you pending list, ',
            'those will be deleted automatically after {allowedDelayDays} days',
            '<br/>',
            '{smallTseImg} As you finish your Tortlets, your score for each dream keeps on increasing.',
            ' Use Dreams tab to see your dream scores.',
            '<br/>',
            '{smallTseImg} Use "Your Score" tab to see your "Tortlets-Score"'
        ],
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'What Are Tortlets'
            }
        ]
    }

});