/*
 * File: app/view/HomePage.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.HomePage', {
    extend: 'Ext.Container',
    alias: 'widget.homePage',

    requires: [
        'MyApp.view.TortletsList',
        'MyApp.view.TodaysTortletList'
    ],

    config: {
        layout: {
            type: 'vbox'
        },
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Tortlets'
            },
            {
                xtype: 'panel',
                flex: 1,
                height: 40,
                layout: {
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'textfield',
                        flex: 9,
                        label: '',
                        name: 'whatsYourDreamTextField',
                        placeHolder: 'What\'s Your Dream ?'
                    },
                    {
                        xtype: 'button',
                        name: 'homePageDreamButton',
                        flex: 1,
                        ui: 'action',
                        text: 'Go'
                    }
                ]
            },
            {
                xtype: 'panel',
                flex: 1,
                height: 40,
                layout: {
                    type: 'fit'
                },
                items: [
                    {
                        xtype: 'segmentedbutton',
                        docked: 'bottom',
                        layout: {
                            align: 'center',
                            pack: 'center',
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'button',
                                name: 'showTodayListButton',
                                pressed: true,
                                ui: 'action',
                                text: 'Today'
                            },
                            {
                                xtype: 'button',
                                name: 'showPendingListButton',
                                ui: 'action',
                                text: 'Pending'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'panel',
                flex: 3,
                layout: {
                    type: 'fit'
                },
                scrollable: 'vertical',
                items: [
                    {
                        xtype: 'tortletsList',
                        hidden: true
                    },
                    {
                        xtype: 'todayTortletsList'
                    }
                ]
            }
        ]
    }

});