/*
 * File: app/view/LandingCardPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.LandingCardPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.landingCardPanel',

    requires: [
        'MyApp.view.loginmodule',
        'MyApp.view.signupmodule',
        'MyApp.view.MainTabPanel'
    ],

    config: {
        itemId: 'landingCardPanel',
        layout: {
            type: 'card'
        },
        items: [
            {
                xtype: 'genericLoginForm'
            },
            {
                xtype: 'registrationCardPanel'
            },
            {
                xtype: 'mainTabPanel'
            }
        ]
    }

});