/*
 * File: app/view/MainTabPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MainTabPanel', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.mainTabPanel',

    requires: [
        'MyApp.view.HomeTabCardPanel',
        'MyApp.view.DreamListCardPanel',
        'MyApp.view.ScoreTabCardPanel',
        'MyApp.view.HelpPanel'
    ],

    config: {
        items: [
            {
                xtype: 'homeTabCardPanel',
                title: 'Home',
                iconCls: 'home'
            },
            {
                xtype: 'dreamListCardPanel',
                title: 'Dreams',
                iconCls: 'star'
            },
            {
                xtype: 'scoretabcardpanel',
                title: 'Your Score',
                iconCls: 'user'
            },
            {
                xtype: 'helpPanel',
                title: 'Help',
                iconCls: 'info'
            }
        ],
        tabBar: {
            docked: 'bottom'
        }
    }

});