/*
 * File: app/view/TortoiseList.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.TortoiseList', {
    extend: 'Ext.dataview.List',
    alias: 'widget.tortoiseList',

    config: {
        hideAnimation: 'wipe',
        showAnimation: 'slide',
        ui: 'round',
        emptyText: 'You need to at least one Tortoise to realize the dream. Tortoise is nothing but an activity to want to do regularly. Remember, slow and steady tortoise wins !',
        scrollToTopOnRefresh: false,
        store: 'tortoisesStore',
        onItemDisclosure: true,
        variableHeights: true,
        itemTpl: [
            '<div>{title}({latestTortoiseScore})</div>',
            '<br/>',
            '.........<img src="static/images/tortoise_smaller.gif"></img>.............!'
        ]
    }

});