/*
 * File: app/view/TortoiseDetails.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.TortoiseDetails', {
    extend: 'Ext.form.Panel',
    alias: 'widget.tortoisedetails',

    config: {
        layout: {
            type: 'vbox'
        },
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Tortoise',
                items: [
                    {
                        xtype: 'button',
                        name: 'tortoiseDetailsBackButton',
                        ui: '',
                        iconCls: 'arrow_up',
                        iconMask: true
                    },
                    {
                        xtype: 'button',
                        name: 'tortoiseDetailsTortletsButton',
                        align: 'right',
                        text: 'Tortlets'
                    }
                ]
            },
            {
                xtype: 'textareafield',
                height: 65,
                labelWidth: '0%',
                placeHolder: 'Workout In Gym or Go Jogging',
                maxRows: 2
            },
            {
                xtype: 'label',
                html: 'To Realize My Dream'
            },
            {
                xtype: 'selectfield',
                label: 'Dream',
                options: [
                    {
                        text: 'Become Healthy, Loose Weight',
                        value: '1'
                    },
                    {
                        text: 'Start my own business',
                        value: '1'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: 'Do It On Every',
                items: [
                    {
                        xtype: 'togglefield',
                        label: 'Monday',
                        labelWidth: '40%'
                    },
                    {
                        xtype: 'togglefield',
                        label: 'Tuesday',
                        labelWidth: '40%'
                    },
                    {
                        xtype: 'togglefield',
                        label: 'Wednesday',
                        labelWidth: '40%'
                    },
                    {
                        xtype: 'togglefield',
                        label: 'Thursday',
                        labelWidth: '40%'
                    },
                    {
                        xtype: 'togglefield',
                        label: 'Friday',
                        labelWidth: '40%'
                    },
                    {
                        xtype: 'togglefield',
                        label: 'Saturday',
                        labelWidth: '40%'
                    },
                    {
                        xtype: 'togglefield',
                        label: 'Sunday',
                        labelWidth: '40%'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                items: [
                    {
                        xtype: 'button',
                        name: 'tortoiseDetailsSaveButton',
                        ui: 'confirm',
                        text: 'Save'
                    }
                ]
            },
            {
                xtype: 'button',
                ui: 'decline',
                text: 'I am Done, Stop The Tortoise..'
            }
        ]
    }

});