/*
 * File: app/controller/DreamsTabController.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.DreamsTabController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            dreamDetails: 'dreamDetails',
            tortoiseDetails: 'tortoiseDetails',
            tortoiseListPanel: 'tortoiseListPanel',
            whatsYourDreamTextField: 'textfield[name=\'whatsYourDreamTextField\']',
            mainTabPanel: 'mainTabPanel',
            dreamListCardPanel: 'dreamListCardPanel',
            dreamDeleteButton: 'button[name=\'dreamDeleteButton\']',
            dreamListPanel: 'dreamListPanel',
            tortoiseDetailsBackToListButton: 'button[name=\'tortoiseDetailsBackToListButton\']',
            tortoiseDetailsBackToDreamButton: 'button[name=\'tortoiseDetailsBackToDreamButton\']',
            tortoiseDeleteButton: 'button[name=\'tortoiseDeleteButton\']'
        },

        control: {
            "dreamList": {
                itemtap: 'onDreamListItemTap'
            },
            "button[name='dreamDetailsNextButton']": {
                tap: 'onDreamDetailsNextButtonTap'
            },
            "button[name='dreamDetailsBackButton']": {
                tap: 'onDreamDetailsBackButtonTap'
            },
            "button[name='tortoiseListStartDreamingButton']": {
                tap: 'onTortoiseListStartDreamingButtonTap'
            },
            "button[name='dreamDeleteButton']": {
                tap: 'onDreamDeleteButtonButtonTap'
            },
            "button[name='tortoiseListPanelBackButton']": {
                tap: 'onTortoiseListPanelBackButtonTap'
            },
            "tortoiseList": {
                itemtap: 'onTortoiseListItemTap'
            },
            "button[name='allTortletsPanelDreamButton']": {
                tap: 'onAllTortletsPanelDreamButtonTap'
            },
            "button[name='tortoiseListPanelAddButton']": {
                tap: 'onTortoiseListPanelAddButtonTap'
            },
            "button[name='tortoiseDetailsSaveButton']": {
                tap: 'onTortoiseDetailsSaveButtonTap'
            },
            "button[name='tortoiseDetailsBackButton']": {
                tap: 'onTortoiseDetailsBackButtonTap'
            },
            "button[name='allTortletsPanelBackButton']": {
                tap: 'onAllTortletsPanelBackButtonTap'
            },
            "button[name='tortoiseDetailsTortletsButton']": {
                tap: 'onTortoiseDetailsTortletsButtonTap'
            },
            "button[name='homePageDreamButton']": {
                tap: 'onHomeTabNewDreamButtonTap'
            },
            "button[name='tortoiseDetailsBackToListButton']": {
                tap: 'onTortoiseDetailsBackToListButtonTap'
            },
            "button[name='tortoiseDetailsBackToDreamButton']": {
                tap: 'onTortoiseDetailsBackHorizontalButtonTap'
            },
            "button[name='tortoiseDeleteButton']": {
                tap: 'onTortoiseDeleteButtonTap'
            },
            "button#mybutton2": {
                tap: 'onTortoiseListStartDreamingButtonTap'
            }
        }
    },

    onDreamListItemTap: function(dataview, index, target, record, e, eOpts) {
        var dreamDetails = this.getDreamDetails();
        dreamDetails.newStatus = 'false';
        dreamDetails.setRecord(record);
        this.getDreamDeleteButton().show();
        this.getDreamListCardPanel().animateActiveItem(dreamDetails, { type: 'slide'} );

    },

    onDreamDetailsNextButtonTap: function(button, e, eOpts) {
        var tortoiseListPanel = this.getTortoiseListPanel();

        var dreamDetailsForm = this.getDreamDetails();
        var newStatus = dreamDetailsForm.newStatus;
        var currentUser = MyApp.app.currentUser;
        /* Accessing global variable which has been set 
        in Application launch() function */
        var userid = MyApp.app.currentUser.get('userid'); 
        var utility = MyApp.app.getController('UtilityController');
        /* Need this so that this controller is available in 
        callback methods. */
        var caller = MyApp.app.getController('DreamsTabController');
        var tempDreamId = MyApp.app.tempId;

        if(newStatus === 'true'){
            var newDream = dreamDetailsForm.getRecord();
            dreamDetailsForm.updateRecord(newDream);
            newDream.set('userid', userid);
            newDream.setTuser(currentUser.getData());
            /* IF u dont do this, id will be posted to server as 
            ext-record-<number>. That will result into exception */
            newDream.set('id',MyApp.app.tempId);
            newDream.save(this.newDreamSave);
        }else{
            var record = dreamDetailsForm.getRecord();
            dreamDetailsForm.updateRecord(record);
            dreamId = record.get('id');
            if(record.dirty === true){
                record.save(this.oldDreamSave);
            }else{
                utility.loadTortoises(dreamId);
                caller.getDreamListCardPanel().animateActiveItem(tortoiseListPanel, {type : 'slide'});
            }

        }

    },

    onDreamDetailsBackButtonTap: function(button, e, eOpts) {
        this.getDreamListCardPanel().animateActiveItem(0, { type : 'slide',direction : 'right'});
    },

    onTortoiseListStartDreamingButtonTap: function(button, e, eOpts) {
        this.getDreamListCardPanel().animateActiveItem(0, {type : 'slide', direction : 'right'});
    },

    onDreamDeleteButtonButtonTap: function(button, e, eOpts) {
        this.getDreamListCardPanel().animateActiveItem(0, { type : 'slide', direction : 'right'});
    },

    onTortoiseListPanelBackButtonTap: function(button, e, eOpts) {
        var dreamDetails = this.getDreamDetails();
        dreamDetails.getScrollable().getScroller().scrollToTop();
        this.getDreamListCardPanel().animateActiveItem(dreamDetails, { type : 'slide', direction : 'right'});
    },

    onTortoiseListItemTap: function(dataview, index, target, record, e, eOpts) {
        var tortoiseDetailsForm = this.getTortoiseDetails();
        tortoiseDetailsForm.setRecord(record);
        tortoiseDetailsForm.newStatus='false';
        var tortoiseDetailsBackToDreamButton = this.getTortoiseDetailsBackToDreamButton();
        tortoiseDetailsBackToDreamButton.show();
        var tortoiseDetailsBackToListButton = this.getTortoiseDetailsBackToListButton();
        tortoiseDetailsBackToListButton.hide();
        var tortoiseDeleteButton =
        this.getTortoiseDeleteButton();
        tortoiseDeleteButton.show();
        tortoiseDetailsForm.getScrollable().getScroller().scrollToTop();
        this.getDreamListCardPanel().animateActiveItem(tortoiseDetailsForm,{ type : 'slide'});
    },

    onAllTortletsPanelDreamButtonTap: function(button, e, eOpts) {
        this.getDreamListCardPanel()
        .animateActiveItem(0,{ type : 'slide', direction : 'right'});
    },

    onTortoiseListPanelAddButtonTap: function(button, e, eOpts) {
        var dreamListCardPanel = this.getDreamListCardPanel();
        var tortoiseDetails = this.getTortoiseDetails();
        var dreamDetailsForm = this.getDreamDetails();
        var dream = dreamDetailsForm.getRecord();
        //dreamDetailsForm.updateRecord(oldDream);
        var newTortoise = Ext.create('MyApp.model.Tortoise', { });
        newTortoise.set('dream', dream.get('id'));
        newTortoise.set('title', '');// Otherwise it uses title of old tortoise ! strange
        tortoiseDetails.setRecord(newTortoise);
        tortoiseDetails.newStatus='true';
        var tortoiseDeleteButton = 
        this.getTortoiseDeleteButton();
        tortoiseDeleteButton.hide();
        var tortoiseDetailsBackToDreamButton 
        = this.getTortoiseDetailsBackToDreamButton();
        tortoiseDetailsBackToDreamButton.hide();
        var tortoiseDetailsBackToListButton 
        = this.getTortoiseDetailsBackToListButton();
        tortoiseDetailsBackToListButton.show();
        dreamListCardPanel.animateActiveItem(tortoiseDetails, { type : 'slide', direction : 'down'});
    },

    onTortoiseDetailsSaveButtonTap: function(button, e, eOpts) {
        var tortoiseListPanel = this.getTortoiseListPanel();

        var tortoiseDetailsForm = this.getTortoiseDetails();
        var newStatus = tortoiseDetailsForm.newStatus;
        var currentUser = MyApp.app.currentUser;

        var userid = MyApp.app.currentUser.get('userid'); 
        var utility = MyApp.app.getController('UtilityController');
        var caller = MyApp.app.getController('DreamsTabController');
        var tempDreamId = MyApp.app.tempId;
        if(newStatus === 'true'){
            var newTortoise = tortoiseDetailsForm.getRecord();
            tortoiseDetailsForm.updateRecord(newTortoise);
            newTortoise.set('userid', userid);
            //alert(newTortoise.getDream().getData());
            newTortoise.setDream(newTortoise.getDream().getData());
            newTortoise.set('id',MyApp.app.tempId);
            newTortoise.save(this.newTortoiseSave);
        }else{
            //alert('old tor');
            var record = tortoiseDetailsForm.getRecord();
            tortoiseDetailsForm.updateRecord(record);
            tortoiseId = record.get('id');
            if(record.dirty === true){
                record.save(this.oldTortoiseSave);
            }else{
                dreamId = record.getDream().get('id');
                utility.loadTortoises(dreamId);
                caller.getDreamListCardPanel().animateActiveItem(tortoiseListPanel, {type : 'slide'});
            }

        }

    },

    onTortoiseDetailsBackButtonTap: function(button, e, eOpts) {
        alert('tortoseDetailsBackToDream');
        var dreamListCardPanel = this.getDreamListCardPanel();
        var tortoiseListPanel = this.getTortoiseListPanel();
        dreamListCardPanel.animateActiveItem(tortoiseListPanel, {type : 'slide', direction : 'right'});
    },

    onAllTortletsPanelBackButtonTap: function(button, e, eOpts) {
        this.getDreamListCardPanel().
        animateActiveItem( 4,{type : 'slide', direction : 'right'});
    },

    onTortoiseDetailsTortletsButtonTap: function(button, e, eOpts) {
        this.getDreamListCardPanel().
        animateActiveItem(3, {type : 'slide'});
    },

    onHomeTabNewDreamButtonTap: function(button, e, eOpts) {
        console.log('inside onHomePageDreamButtonTap');
        var dreamForm = this.getDreamDetails();
        var text = this.getWhatsYourDreamTextField().getValue();
        //alert(text);
        var record = Ext.create('MyApp.model.Dream');
        record.set('title', text);
        dreamForm.newStatus='true';
        dreamForm.setRecord(record);
        var mainTabPanel = this.getMainTabPanel();
        mainTabPanel.setActiveItem(1);
        var deleteButton = this.getDreamDeleteButton(); //Ext.ComponentQuery.query("button[name='dreamDeleteButton']");
        deleteButton.hide();
        dreamForm.getScrollable().getScroller().scrollToTop();
        this.getDreamListCardPanel().animateActiveItem(dreamForm, { type: 'slide'});

    },

    onTortoiseDetailsBackToListButtonTap: function(button, e, eOpts) {
        var tortoiseListPanel = this.getTortoiseListPanel();
        var slideConfig =  { type : 'slide', direction : 'up'}; 
        this.getDreamListCardPanel().animateActiveItem(tortoiseListPanel,slideConfig);
    },

    onTortoiseDetailsBackHorizontalButtonTap: function(button, e, eOpts) {
        var tortoiseListPanel = this.getTortoiseListPanel();
        var slideConfig =  { type : 'slide', direction : 'right'}; 
        this.getDreamListCardPanel().animateActiveItem(tortoiseListPanel,slideConfig);
    },

    onTortoiseDeleteButtonTap: function(button, e, eOpts) {

    },

    onTortoiseListStartDreamingButtonTap: function(button, e, eOpts) {
        var dreamDetails = this.getDreamDetails();
        this.getDreamListCardPanel().animateActiveItem(dreamDetails, { type : 'slide', direction : 'right'});
    },

    newDreamSave: function(createdModel) {
        var utility = MyApp.app.getController('UtilityController');
        var dreamsTabController = MyApp.app.getController('DreamsTabController');
        var tortoiseListPanel = dreamsTabController.getTortoiseListPanel();
        var dreamId = createdModel.get('id');
        var dreamDetailsForm = dreamsTabController.getDreamDetails();
        dreamDetailsForm.setRecord(createdModel);
        var dreamsStore = Ext.getStore('dreamsStore');
        dreamsStore.load();
        utility.loadTortoises(dreamId);
        dreamsTabController.getDreamListCardPanel().animateActiveItem(tortoiseListPanel, {type : 'slide'});

    },

    oldDreamSave: function(savedModel) {
        var utility = MyApp.app.getController('UtilityController');
        var dreamsTabController = MyApp.app.getController('DreamsTabController');
        var tortoiseListPanel = dreamsTabController.getTortoiseListPanel();
        var dreamId = savedModel.get('id');
        var dreamsStore = Ext.getStore('dreamsStore');
        dreamsStore.load();
        utility.loadTortoises(dreamId);
        dreamsTabController.getDreamListCardPanel().animateActiveItem(tortoiseListPanel, {type : 'slide'});

    },

    newTortoiseSave: function(createdModel) {
        var utility = MyApp.app.getController('UtilityController');
        var dreamsTabController = MyApp.app.getController('DreamsTabController');
        var tortoiseListPanel = dreamsTabController.getTortoiseListPanel();
        var dream = createdModel.get('dream');
        dreamId = dream.id;
        utility.loadTortoises(dreamId);
        dreamsTabController.getDreamListCardPanel().animateActiveItem(tortoiseListPanel, {type : 'slide', direction : 'up'});

    },

    oldTortoiseSave: function(savedModel) {
        var utility = MyApp.app.getController('UtilityController');
        var dreamsTabController = MyApp.app.getController('DreamsTabController');
        var tortoiseListPanel = dreamsTabController.getTortoiseListPanel();
        var dream = savedModel.get('dream');
        dreamId = dream.id;
        utility.loadTortoises(dreamId);
        dreamsTabController.getDreamListCardPanel().animateActiveItem(tortoiseListPanel, {type : 'slide', direction : 'up'});

    }

});