/*
 * File: app/controller/UtilityController.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.UtilityController', {
    extend: 'Ext.app.Controller',

    config: {
    },

    loadTortoises: function(dreamId) {
        console.log('inside loadTortoises');
        var tortoisesStore = Ext.getStore('tortoisesStore');
        var proxy = tortoisesStore.getProxy();
        var orgUrl = proxy.getUrl();
        var urlWithDream = orgUrl + '&dream=' + dreamId;
        proxy.setUrl(urlWithDream);
        tortoisesStore.load();
        console.log('loaded tortoisesStore');
        proxy.setUrl(orgUrl);
        console.log('getting out of loadTortoises');
    },

    init: function(application) {
        console.log('initing UtilityController');
    },

    launch: function() {
        console.log('launching UtilityController');
    }

});