/*
 * File: app/view/RegistrationCardPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.RegistrationCardPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.registrationCardPanel',

    config: {
        registrationUrl: 'http://localhost:8080/tusers',
        itemId: 'registrationCardPanelItemId',
        layout: {
            type: 'card'
        },
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Sign Up !'
            },
            {
                xtype: 'formpanel',
                itemId: 'registrationPage1',
                items: [
                    {
                        xtype: 'fieldset',
                        title: 'Personal Details',
                        items: [
                            {
                                xtype: 'textfield',
                                itemId: 'firstName',
                                label: 'First Name',
                                labelWidth: '37%'
                            },
                            {
                                xtype: 'textfield',
                                itemId: 'lastName',
                                label: 'Last Name',
                                labelWidth: '37%'
                            },
                            {
                                xtype: 'emailfield',
                                itemId: 'userEmail',
                                label: 'Email',
                                labelWidth: '37%',
                                placeHolder: 'email@example.com'
                            },
                            {
                                xtype: 'emailfield',
                                itemId: 'confirmEmail',
                                label: 'Confirm Email',
                                labelWidth: '37%',
                                placeHolder: 'email@example.com'
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        title: 'Credentials',
                        items: [
                            {
                                xtype: 'textfield',
                                itemId: 'userid',
                                label: 'User Id',
                                labelWidth: '37%'
                            },
                            {
                                xtype: 'passwordfield',
                                itemId: 'password',
                                label: 'Password',
                                labelWidth: '37%'
                            },
                            {
                                xtype: 'passwordfield',
                                itemId: 'confirmedPassword',
                                label: 'Confirm',
                                labelWidth: '37%'
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        itemId: 'myfieldset2',
                        items: [
                            {
                                xtype: 'button',
                                handler: function(button, event) {
                                    var registrationCardPanel = this.up('registrationCardPanel');

                                    var firstName = registrationCardPanel.down('#firstName');
                                    var lastName = registrationCardPanel.down('#lastName');
                                    var userEmail = registrationCardPanel.down('#userEmail');
                                    var confirmEmail = registrationCardPanel.down('#confirmEmail');

                                    var userid = registrationCardPanel.down('#userid');
                                    var password = registrationCardPanel.down('#password');
                                    var confirmedPassword = registrationCardPanel.down('#confirmedPassword');

                                    var userObject = {};

                                    userObject.firstName = firstName.getValue();
                                    userObject.lastName = lastName.getValue();
                                    userObject.userEmail = userEmail.getValue();
                                    userObject.confirmEmail = confirmEmail.getValue();

                                    userObject.userid = userid.getValue();
                                    userObject.password = password.getValue();
                                    userObject.retypePassword = confirmedPassword.getValue();
                                    userObject.status = 'ACTIVE';

                                    //////////////////////Validations////////////////////////////////
                                    var nameRgx = /^[A-Za-z ]{3,20}$/;
                                    var emailRgx = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
                                    var useridRgx = /^[A-Za-z0-9_]{6,16}$/;
                                    var passwordRgx =  /^[A-Za-z0-9!@#$%^&*()_]{6,100}$/;
                                    var errors = [];

                                    for(var field in userObject){
                                        console.log(field + ': ' + userObject[field]);
                                        if(userObject[field] === ''){
                                            Ext.Msg.alert('','All fields are mandatory !',Ext.emptyFn);
                                            errors[errors.length] = 'All fields are mandatory !';
                                            return;
                                        }
                                    }

                                    if(! nameRgx.test(userObject.firstName)){
                                        Ext.Msg.alert('','First Name format invalid',Ext.emptyFn); 
                                        errors[errors.length] = 'First Name format invalid !';
                                        return;
                                    }


                                    if(! nameRgx.test(userObject.lastName)){
                                        Ext.Msg.alert('','Last Name format invalid',Ext.emptyFn);
                                        errors[errors.length] = 'Last Name format invalid !';
                                        return;
                                    }


                                    if(! emailRgx.test(userObject.userEmail)){
                                        Ext.Msg.alert('','Email format invalid',Ext.emptyFn); 
                                        errors[errors.length] = 'Email format invalid';
                                        return;
                                    }

                                    if(userObject.userEmail !== userObject.confirmEmail) {
                                        Ext.Msg.alert('','Emails do not match !',Ext.emptyFn);
                                        errors[errors.length] =  'Emails do not match !';
                                        return;
                                    }


                                    if(! useridRgx.test(userObject.userid)){
                                        Ext.Msg.alert('','Userid Invalid, must be 6 in length, no special symbols',Ext.emptyFn); 
                                        errors[errors.length] =  'Userid Invalid, must be 6 in length, no special symbols';
                                        return;
                                    }

                                    if(! useridRgx.test(userObject.password)){
                                        Ext.Msg.alert('','Password invalid, Min 6 in length, allowed a-z,0-9 and symbols !@#$%^&*()_',Ext.emptyFn); 
                                        errors[errors.length] = 'Password invalid, Min 6 in length, allowed a-z,0-9 and symbols !@#$%^&*()_';
                                        return;
                                    }


                                    if(userObject.password !== userObject.confirmPassword) {
                                        Ext.Msg.alert('','Passwords do not match !',Ext.emptyFn);
                                        errors[errors.length] = 'Passwords do not match !';
                                        return;
                                    }

                                    Ext.Msg.alert('','testing mode',Ext.emptyFn);
                                    return;
                                    /*
                                    // Remember in order to report all errors at once, you have to remove all return statements.
                                    var msg = "Please Enter Valide Data...\n";
                                    for (var i = 0; i<errors.length; i++) {
                                        var numError = i + 1;
                                        msg += "\n" + numError + ". " + errors[i];
                                    }
                                    alert(msg);
                                    */
                                    /////////////////////////////////////////////////////////////////
                                    var userObjectJson = Ext.JSON.encode(userObject);


                                    var registrationUrl = registrationCardPanel.getInitialConfig().registrationUrl;

                                    Ext.Ajax.request({
                                        url: registrationUrl,
                                        method: 'post',
                                        jsonData : userObjectJson,
                                        headers : { 
                                            Accept : 'application/json' 
                                        },
                                        success: function (response) { 
                                            alert('signUpSuccess');
                                            //var loginResponse = Ext.JSON.decode(response.responseText);
                                            //var userObject = loginResponse[0];
                                            //if (loginResponse.length === 1 && userObject.userid === userid) {
                                            //    userObject.plainPassword = password;
                                            //   me.fireEvent('signUpSuccess',loginResponse[0]);
                                            //} else {
                                            //    me.showSignInFailedMessage('Bad Credentials');
                                            //}
                                        },
                                        failure: function (response) {
                                            //me.showSignInFailedMessage('Server error. Please try again later.');
                                            alert('signUpFailure');
                                        }
                                    });

                                },
                                itemId: 'signUpNextButton',
                                ui: 'action',
                                text: 'Next'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'panel',
                html: 'Registration Successful !',
                itemId: 'registrationPage2',
                items: [
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            var registrationCardPanel = this.up('registrationCardPanel');
                            registrationCardPanel.fireEvent('signUpSuccess',button);
                        },
                        text: 'Go To Sign In'
                    }
                ]
            }
        ]
    }

});