/*
 * File: app/view/RegistrationCardPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.RegistrationCardPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.registrationCardPanel',

    config: {
        registrationUrl: 'http://localhost:8080/tusers',
        itemId: 'registrationCardPanelItemId',
        layout: {
            type: 'card'
        },
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Sign Up !'
            },
            {
                xtype: 'formpanel',
                itemId: 'whatsYourNameForm',
                items: [
                    {
                        xtype: 'fieldset',
                        title: 'Whats Your Name, Buddy !',
                        items: [
                            {
                                xtype: 'textfield',
                                itemId: 'firstNameAsUserId',
                                placeHolder: 'Enter your first name..'
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        title: 'Type any word you like ..',
                        items: [
                            {
                                xtype: 'textfield',
                                itemId: 'wordYouLike',
                                labelWidth: '0%',
                                placeHolder: 'Temporary password..'
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        itemId: 'whatsYourNameFormSubmit',
                        items: [
                            {
                                xtype: 'button',
                                handler: function(button, event) {
                                    var registrationCardPanel = this.up('registrationCardPanel');

                                    var whatsYourNameForm = registrationCardPanel.down('#whatsYourNameForm');

                                    var firstNameAsUserid = whatsYourNameForm.down('#firstNameAsUserId');
                                    var wordYouLike = whatsYourNameForm.down('#wordYouLike');

                                    firstNameAsUserid = firstNameAsUserid.getValue();
                                    wordYouLike = wordYouLike.getValue();


                                    var userObject = {};

                                    userObject.userid = firstNameAsUserid;
                                    userObject.password = wordYouLike;

                                    var nameRgx = /^[A-Za-z ]{3,20}$/;
                                    var errors = [];

                                    for(var field in userObject){
                                        console.log(field + ': ' + userObject[field]);
                                        if(userObject[field] === ''){
                                            var msg = 'Fields Are Mandatory !';
                                            Ext.Msg.alert('',msg,Ext.emptyFn);
                                            errors[errors.length] = msg;
                                            return;
                                        }
                                    }

                                    if(! nameRgx.test(userObject.userid)){
                                        var msg = 'Name is invalid ! At least 3 in length and no spaces. You could append last name';
                                        Ext.Msg.alert('',msg,Ext.emptyFn); 
                                        errors[errors.length] = msg;
                                        return;
                                    }

                                    //TODO : Need to add validation for worldYouLike


                                    userObject.firstName = firstNameAsUserid;

                                    userObject.status = 'ACTIVE';

                                    var userObjectJson = Ext.JSON.encode(userObject);


                                    var registrationUrl = registrationCardPanel.getInitialConfig().registrationUrl;

                                    Ext.Ajax.request({
                                        url: registrationUrl,
                                        method: 'post',
                                        jsonData : userObjectJson,
                                        headers : { 
                                            Accept : 'application/json' 
                                        },
                                        success: function (response) { 
                                            var userObject = Ext.JSON.decode(response.responseText);       
                                            userObject.plainPassword = wordYouLike;

                                            if (userObject.createdOn !== null) {
                                                //registrationCardPanel.fireEvent('signUpSuccess',userObject);
                                                var quickSignUpDoneForm = registrationCardPanel.down('#quickSignUpDoneForm');
                                                var generatedUserId = quickSignUpDoneForm.down('#generatedUserId');
                                                generatedUserId.setValue(userObject.userid);
                                                var wordAsPassword = quickSignUpDoneForm.down('#wordAsPassword');
                                                wordAsPassword.setValue(userObject.plainPassword);

                                                registrationCardPanel.setActiveItem(2);
                                            } else {
                                                alert('Either return userObject had no same userid or two objects returned');
                                            }
                                        },
                                        failure: function (response) {
                                            //me.showSignInFailedMessage('Server error. Please try again later.');
                                            var msg = 'Server error, try later';
                                            Ext.Msg.alert('',msg,Ext.emptyFn);
                                        }
                                    });



                                },
                                itemId: 'whatsYourNameFormButton',
                                ui: 'action',
                                text: 'Sign Up !'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'formpanel',
                itemId: 'registrationPage1',
                items: [
                    {
                        xtype: 'fieldset',
                        title: 'Personal Details',
                        items: [
                            {
                                xtype: 'textfield',
                                itemId: 'firstName',
                                label: 'First Name',
                                labelWidth: '37%'
                            },
                            {
                                xtype: 'textfield',
                                itemId: 'lastName',
                                label: 'Last Name',
                                labelWidth: '37%'
                            },
                            {
                                xtype: 'emailfield',
                                itemId: 'userEmail',
                                label: 'Email',
                                labelWidth: '37%',
                                placeHolder: 'email@example.com'
                            },
                            {
                                xtype: 'emailfield',
                                itemId: 'confirmEmail',
                                label: 'Confirm Email',
                                labelWidth: '37%',
                                placeHolder: 'email@example.com'
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        title: 'Credentials',
                        items: [
                            {
                                xtype: 'textfield',
                                itemId: 'userid',
                                label: 'User Id',
                                labelWidth: '37%'
                            },
                            {
                                xtype: 'passwordfield',
                                itemId: 'password',
                                label: 'Password',
                                labelWidth: '37%'
                            },
                            {
                                xtype: 'passwordfield',
                                itemId: 'confirmedPassword',
                                label: 'Confirm',
                                labelWidth: '37%'
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        itemId: 'myfieldset2',
                        items: [
                            {
                                xtype: 'button',
                                handler: function(button, event) {
                                    var registrationCardPanel = this.up('registrationCardPanel');

                                    var firstName = registrationCardPanel.down('#firstName');
                                    var lastName = registrationCardPanel.down('#lastName');
                                    var userEmail = registrationCardPanel.down('#userEmail');
                                    var confirmEmail = registrationCardPanel.down('#confirmEmail');

                                    var userid = registrationCardPanel.down('#userid');
                                    var password = registrationCardPanel.down('#password');
                                    var confirmedPassword = registrationCardPanel.down('#confirmedPassword');

                                    var userObject = {};

                                    userObject.firstName = firstName.getValue();
                                    userObject.lastName = lastName.getValue();
                                    userObject.userEmail = userEmail.getValue();
                                    userObject.confirmEmail = confirmEmail.getValue();

                                    userObject.userid = userid.getValue();
                                    userObject.password = password.getValue();
                                    userObject.confirmedPassword = confirmedPassword.getValue();
                                    userObject.status = 'ACTIVE';

                                    //////////////////////Validations////////////////////////////////
                                    var nameRgx = /^[A-Za-z ]{3,20}$/;
                                    var emailRgx = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
                                    var useridRgx = /^[A-Za-z0-9_]{6,16}$/;
                                    var passwordRgx =  /^[A-Za-z0-9!@#$%^&*()_]{6,100}$/;
                                    var errors = [];

                                    for(var field in userObject){
                                        console.log(field + ': ' + userObject[field]);
                                        if(userObject[field] === ''){
                                            Ext.Msg.alert('','All fields are mandatory !',Ext.emptyFn);
                                            errors[errors.length] = 'All fields are mandatory !';
                                            return;
                                        }
                                    }

                                    if(! nameRgx.test(userObject.firstName)){
                                        Ext.Msg.alert('','First Name format invalid',Ext.emptyFn); 
                                        errors[errors.length] = 'First Name format invalid !';
                                        return;
                                    }


                                    if(! nameRgx.test(userObject.lastName)){
                                        Ext.Msg.alert('','Last Name format invalid',Ext.emptyFn);
                                        errors[errors.length] = 'Last Name format invalid !';
                                        return;
                                    }


                                    if(! emailRgx.test(userObject.userEmail)){
                                        Ext.Msg.alert('','Email format invalid',Ext.emptyFn); 
                                        errors[errors.length] = 'Email format invalid';
                                        return;
                                    }

                                    if(userObject.userEmail !== userObject.confirmEmail) {
                                        Ext.Msg.alert('','Emails do not match !',Ext.emptyFn);
                                        errors[errors.length] =  'Emails do not match !';
                                        return;
                                    }


                                    if(! useridRgx.test(userObject.userid)){
                                        Ext.Msg.alert('','Userid Invalid, must be 6 in length, no special symbols',Ext.emptyFn); 
                                        errors[errors.length] =  'Userid Invalid, must be 6 in length, no special symbols';
                                        return;
                                    }

                                    if(! useridRgx.test(userObject.password)){
                                        Ext.Msg.alert('','Password invalid, Min 6 in length, allowed a-z,0-9 and symbols !@#$%^&*()_',Ext.emptyFn); 
                                        errors[errors.length] = 'Password invalid, Min 6 in length, allowed a-z,0-9 and symbols !@#$%^&*()_';
                                        return;
                                    }


                                    if(userObject.password !== userObject.confirmedPassword) {
                                        Ext.Msg.alert('','Passwords do not match !',Ext.emptyFn);
                                        errors[errors.length] = 'Passwords do not match !';
                                        return;
                                    }

                                    /*
                                    // Remember in order to report all errors at once, you have to remove all return statements.
                                    var msg = "Please Enter Valide Data...\n";
                                    for (var i = 0; i<errors.length; i++) {
                                        var numError = i + 1;
                                        msg += "\n" + numError + ". " + errors[i];
                                    }
                                    alert(msg);
                                    */
                                    /////////////////////////////////////////////////////////////////
                                    var userObjectJson = Ext.JSON.encode(userObject);


                                    var registrationUrl = registrationCardPanel.getInitialConfig().registrationUrl;

                                    Ext.Ajax.request({
                                        url: registrationUrl,
                                        method: 'post',
                                        jsonData : userObjectJson,
                                        headers : { 
                                            Accept : 'application/json' 
                                        },
                                        success: function (response) { 
                                            alert('signUpSuccess');
                                            var loginResponse = Ext.JSON.decode(response.responseText);
                                            var userObject = loginResponse[0];
                                            if (loginResponse.length === 1 && userObject.userid === userid) {
                                                userObject.plainPassword = password;
                                                registrationCardPanel.fireEvent('signUpSuccess',loginResponse[0]);
                                            } else {
                                                alert('Either return userObject had no same userid or two objects returned');
                                            }
                                        },
                                        failure: function (response) {
                                            //me.showSignInFailedMessage('Server error. Please try again later.');
                                            alert('signUpFailure');
                                        }
                                    });

                                },
                                itemId: 'signUpNextButton',
                                ui: 'action',
                                text: 'Next'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'formpanel',
                itemId: 'quickSignUpDoneForm',
                items: [
                    {
                        xtype: 'label',
                        html: '<h1>Quick Sign Up Done !</h1> <br/> <p style="font-size:small">You can now use following auto-generated credentials on any device. This screen is shown only once ! </p>',
                        ui: 'light'
                    },
                    {
                        xtype: 'fieldset',
                        itemId: 'generatedUserIdFieldSet',
                        title: '',
                        items: [
                            {
                                xtype: 'textfield',
                                disabled: true,
                                itemId: 'generatedUserId',
                                label: 'Userid',
                                labelWidth: '40%'
                            },
                            {
                                xtype: 'textfield',
                                disabled: true,
                                itemId: 'wordAsPassword',
                                label: 'Password',
                                labelWidth: '40%'
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        items: [
                            {
                                xtype: 'button',
                                handler: function(button, event) {
                                    var registrationCardPanel = this.up('registrationCardPanel');
                                    registrationCardPanel.fireEvent('signUpSuccess',button);
                                },
                                ui: 'action',
                                text: 'Start Using App !'
                            }
                        ]
                    },
                    {
                        xtype: 'label',
                        html: '<p style="font-size:small"> Click here, If you want to edit credentials and continue to full-fledge secure registration. </p>'
                    },
                    {
                        xtype: 'fieldset',
                        title: '',
                        items: [
                            {
                                xtype: 'button',
                                ui: 'confirm',
                                text: 'Secure Sign Up !'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});