/*
 * File: app/view/RegistrationCardPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.RegistrationCardPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.registrationCardPanel',

    config: {
        itemId: 'registrationCardPanelItemId',
        layout: {
            type: 'card'
        },
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Sign Up !'
            },
            {
                xtype: 'formpanel',
                itemId: 'registrationPage1',
                items: [
                    {
                        xtype: 'fieldset',
                        title: 'Personal Details',
                        items: [
                            {
                                xtype: 'textfield',
                                itemId: 'firstName',
                                label: 'First Name',
                                labelWidth: '37%'
                            },
                            {
                                xtype: 'textfield',
                                itemId: 'lastName',
                                label: 'Last Name',
                                labelWidth: '37%'
                            },
                            {
                                xtype: 'emailfield',
                                itemId: 'userEmail',
                                label: 'Email',
                                labelWidth: '37%',
                                placeHolder: 'email@example.com'
                            },
                            {
                                xtype: 'emailfield',
                                itemId: 'confirmEmail',
                                label: 'Confirm Email',
                                labelWidth: '37%',
                                placeHolder: 'email@example.com'
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        title: 'Credentials',
                        items: [
                            {
                                xtype: 'textfield',
                                itemId: 'userid',
                                label: 'User Id',
                                labelWidth: '37%'
                            },
                            {
                                xtype: 'passwordfield',
                                itemId: 'password',
                                label: 'Password',
                                labelWidth: '37%'
                            },
                            {
                                xtype: 'textfield',
                                itemId: 'confirmedPassword',
                                label: 'Confirm',
                                labelWidth: '37%'
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        itemId: 'myfieldset2',
                        items: [
                            {
                                xtype: 'button',
                                handler: function(button, event) {
                                    var registrationCardPanel = this.up('registrationCardPanel');

                                    var firstName = registrationCardPanel.down('#firstName');

                                    firstName = firstName.getValue();


                                    registrationCardPanel.animateActiveItem(1,{type:'slide', direction:'left'});
                                },
                                itemId: 'signUpNextButton',
                                ui: 'action',
                                text: 'Next'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'panel',
                html: 'Registration Successful !',
                itemId: 'registrationPage2',
                items: [
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            var registrationCardPanel = this.up('registrationCardPanel');
                            registrationCardPanel.fireEvent('signUpSuccess',button);
                        },
                        text: 'Go To Sign In'
                    }
                ]
            }
        ]
    }

});