// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.softrism.tortlets.vo;

import com.softrism.tortlets.vo.DayVO;
import java.io.Serializable;

privileged aspect DayVO_Roo_Serializable {
    
    declare parents: DayVO implements Serializable;
    
    private static final long DayVO.serialVersionUID = 1L;
    
}
