/*
 * File: app/view/HomePage.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.HomePage', {
    extend: 'Ext.Container',
    alias: 'widget.homePage',

    requires: [
        'MyApp.view.TortletsListsContainerPanel'
    ],

    config: {
        layout: {
            type: 'vbox'
        },
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Tortlets'
            },
            {
                xtype: 'panel',
                flex: 2,
                docked: 'top',
                height: 40,
                layout: {
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'textfield',
                        flex: 9,
                        label: '',
                        labelWidth: 0,
                        name: 'whatsYourDreamTextField',
                        placeHolder: 'What\'s Your Dream ?'
                    },
                    {
                        xtype: 'button',
                        name: 'homePageDreamButton',
                        flex: 1,
                        docked: 'right',
                        ui: 'action',
                        text: 'Go'
                    }
                ]
            },
            {
                xtype: 'panel',
                flex: 2,
                centered: false,
                height: 40,
                margin: '',
                layout: {
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'panel',
                        flex: 1,
                        items: [
                            {
                                xtype: 'button',
                                name: 'homePageRefreshButton',
                                centered: true,
                                docked: 'bottom',
                                ui: 'action-small',
                                iconCls: 'refresh'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        flex: 3,
                        items: [
                            {
                                xtype: 'segmentedbutton',
                                name: 'mainPageSegmentedButton',
                                centered: true,
                                docked: 'bottom',
                                ui: '',
                                layout: {
                                    align: 'end',
                                    pack: 'end',
                                    type: 'hbox'
                                },
                                items: [
                                    {
                                        xtype: 'button',
                                        name: 'showTodayListButton',
                                        pressed: true,
                                        ui: 'action',
                                        text: 'Today'
                                    },
                                    {
                                        xtype: 'button',
                                        name: 'showPendingListButton',
                                        ui: 'action',
                                        text: 'Pending'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        flex: 1,
                        items: [
                            {
                                xtype: 'button',
                                name: 'homePageHelpButton',
                                centered: true,
                                docked: 'bottom',
                                ui: 'action-small',
                                text: '<b>?</b>'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'tortletsListsContainerPanel',
                flex: 16
            }
        ]
    }

});