/*
 * File: app/view/HomeTabCardPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.HomeTabCardPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.homeTabCardPanel',

    requires: [
        'MyApp.view.HomePage',
        'MyApp.view.DreamDetails',
        'MyApp.view.TortletsDetails'
    ],

    config: {
        layout: {
            type: 'card'
        },
        listeners: [
            {
                fn: 'onPanelShow',
                event: 'show'
            }
        ],
        items: [
            {
                xtype: 'homePage'
            },
            {
                xtype: 'dreamDetails'
            },
            {
                xtype: 'tortletDetails'
            }
        ]
    },

    onPanelShow: function(component, eOpts) {
        component.setActiveItem(0);
    }

});