/*
 * File: app/view/TortoiseList.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.TortoiseList', {
    extend: 'Ext.dataview.List',
    alias: 'widget.tortoiseList',

    config: {
        hideAnimation: 'wipe',
        showAnimation: 'slide',
        ui: 'round',
        emptyText: 'You need to at least one Tortoise to realize the dream. Tortoise is nothing but an activity to want to do regularly. Remember, slow and steady tortoise wins !',
        store: 'tortoisesStore',
        onItemDisclosure: true,
        variableHeights: true,
        itemTpl: [
            '<div>{title}</div>',
            '',
            '',
            '{%',
            '',
            'var maxScore = 100;',
            'var done = \'\';',
            'for(i=10; i < maxScore+1; i=i+10) {    ',
            '	if(i <= values.latestTortoiseScore) {',
            '%}',
            '        ..',
            '{%',
            '     }else{',
            '        if(done !== \'true\'){',
            '%}',
            '           <img src="static/images/tortoise_smaller.png"></img>',
            '{%',
            '            done = \'true\';',
            '        }else{',
            '%}',
            '          .. ',
            '{%',
            '        }',
            '	}',
            '}',
            '%}',
            '',
            '{%',
            'if(values.latestTortoiseScore >= 100) {',
            '%}',
            '&nbsp;..',
            '<img src="static/images/race-finish-small.png"></img>',
            '<img src="static/images/tortoise_smaller.png"></img>',
            '{%',
            '}else {',
            '%}',
            '<img src="static/images/race-finish-small.png"></img>',
            '{%',
            '}',
            '%}',
            '<span class="smallFont">(Score:{latestTortoiseScore})</span>',
            ''
        ]
    }

});