/*
 * File: app/view/TortletsList.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.TortletsList', {
    extend: 'Ext.dataview.List',
    alias: 'widget.tortletsList',

    config: {
        ui: 'round',
        scrollToTopOnRefresh: false,
        store: 'incompleteTortletsStore',
        grouped: true,
        onItemDisclosure: false,
        variableHeights: true,
        itemTpl: [
            '{title}<span class="smallFont"> ({tortoise.duration}min)</span>',
            '<br/>',
            '<span class="smallFont">Dream: {tortoise.dream.title}</span>'
        ],
        listeners: [
            {
                fn: 'onListPainted',
                event: 'painted'
            }
        ]
    },

    onListPainted: function(element, eOpts) {
        var tortletList = this;
        var dreamStore = Ext.getStore('dreamsStore');
        dreamStore.load(function(records, operation, success) {
            if(records.length === 0){
                tortletList.setEmptyText('You need to have dreams to have Tortlets');
            }else{
                tortletList.setEmptyText('Wow ! Nothing pending. You are really on top of everything !');
            }   
        }, this);
    }

});